// Menu data for the restaurant
export const menuCategories = [
  { id: 'all', name: 'ทั้งหมด', icon: '' },
  { id: 'appetizer', name: 'อาหารเรียกน้ำย่อย', icon: '' },
  { id: 'main', name: 'จานหลัก', icon: '' },
  { id: 'noodle', name: 'ก๋วยเตี๋ยว & เส้น', icon: '' },
  { id: 'grill', name: 'ปิ้งย่าง', icon: '' },
  { id: 'seafood', name: 'อาหารทะเล', icon: '' },
  { id: 'dessert', name: 'ของหวาน', icon: '' },
  { id: 'drink', name: 'เครื่องดื่ม', icon: '' },
];

export const menuItems = [
  // Appetizers
  {
    id: 1,
    name: 'สลัดแซลมอนรมควัน',
    nameEn: 'Smoked Salmon Salad',
    description: 'สลัดผักสดกับแซลมอนรมควัน ราดซอสมะนาวน้ำผึ้ง',
    price: 189,
    category: 'appetizer',
    image: '',
    popular: true,
    spicyLevel: 0,
  },
  {
    id: 2,
    name: 'เกี๊ยวซ่าหมู',
    nameEn: 'Pork Gyoza',
    description: 'เกี๊ยวซ่าไส้หมูสับเนื้อแน่น ทอดกรอบ เสิร์ฟพร้อมซอสพอนซึ',
    price: 129,
    category: 'appetizer',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 3,
    name: 'ปอเปี๊ยะทอดไส้ผัก',
    nameEn: 'Vegetable Spring Rolls',
    description: 'ปอเปี๊ยะทอดกรอบไส้ผักรวม เสิร์ฟพร้อมซอสบ๊วย',
    price: 99,
    category: 'appetizer',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 4,
    name: 'ต้มยำกุ้ง',
    nameEn: 'Tom Yum Goong',
    description: 'ต้มยำกุ้งน้ำข้น รสเข้มข้น เต็มไปด้วยกุ้งสดและเห็ด',
    price: 199,
    category: 'appetizer',
    image: '',
    popular: true,
    spicyLevel: 3,
  },

  // Main courses
  {
    id: 5,
    name: 'แกงเขียวหวานไก่',
    nameEn: 'Green Curry Chicken',
    description: 'แกงเขียวหวานไก่หอมมะพร้าวกะทิ เสิร์ฟพร้อมข้าวหอมมะลิ',
    price: 169,
    category: 'main',
    image: '',
    popular: true,
    spicyLevel: 2,
  },
  {
    id: 6,
    name: 'ข้าวผัดปู',
    nameEn: 'Crab Fried Rice',
    description: 'ข้าวผัดเนื้อปูก้อนใหญ่ ผัดกับไข่และผักสด',
    price: 219,
    category: 'main',
    image: '',
    popular: true,
    spicyLevel: 0,
  },
  {
    id: 7,
    name: 'กะเพราหมูสับ',
    nameEn: 'Basil Minced Pork',
    description: 'กะเพราหมูสับผัดกรอบ ไข่ดาว เสิร์ฟพร้อมข้าวสวย',
    price: 119,
    category: 'main',
    image: '',
    popular: true,
    spicyLevel: 2,
  },
  {
    id: 8,
    name: 'สเต็กเนื้อวากิว',
    nameEn: 'Wagyu Beef Steak',
    description: 'สเต็กเนื้อวากิว A5 ย่างระดับ Medium Rare พร้อมซอสพริกไทยดำ',
    price: 899,
    category: 'main',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 9,
    name: 'แซลมอนเทอริยากิ',
    nameEn: 'Teriyaki Salmon',
    description: 'แซลมอนย่างซอสเทอริยากิ เสิร์ฟพร้อมข้าวญี่ปุ่นและผักต้ม',
    price: 329,
    category: 'main',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 10,
    name: 'ผัดกระเพราทะเล',
    nameEn: 'Spicy Seafood Basil',
    description: 'ผัดกระเพราทะเลรวม กุ้ง หมึก หอย พริกสด',
    price: 249,
    category: 'main',
    image: '',
    popular: false,
    spicyLevel: 3,
  },

  // Noodles
  {
    id: 11,
    name: 'ผัดไทยกุ้งสด',
    nameEn: 'Pad Thai with Shrimp',
    description: 'ผัดไทยเส้นจันท์กุ้งสดตัวใหญ่ โรยถั่วป่นและมะนาว',
    price: 179,
    category: 'noodle',
    image: '',
    popular: true,
    spicyLevel: 1,
  },
  {
    id: 12,
    name: 'ราเมนหมูชาชู',
    nameEn: 'Chashu Pork Ramen',
    description: 'ราเมนน้ำซุปกระดูกเข้มข้น หมูชาชูนุ่ม ไข่ยางมะตูม',
    price: 229,
    category: 'noodle',
    image: '',
    popular: true,
    spicyLevel: 0,
  },
  {
    id: 13,
    name: 'บะหมี่เกี๊ยวหมูแดง',
    nameEn: 'Red Pork Wonton Noodle',
    description: 'บะหมี่เหนียวนุ่มกับหมูแดงหอมเครื่องเทศ เกี๊ยวกุ้งสด',
    price: 119,
    category: 'noodle',
    image: '',
    popular: false,
    spicyLevel: 0,
  },

  // Grill
  {
    id: 14,
    name: 'หมูสะเต๊ะ',
    nameEn: 'Pork Satay',
    description: 'หมูสะเต๊ะย่างหอม 8 ไม้ พร้อมซอสถั่วและอาจาด',
    price: 149,
    category: 'grill',
    image: '',
    popular: true,
    spicyLevel: 0,
  },
  {
    id: 15,
    name: 'ซี่โครงหมูบาร์บีคิว',
    nameEn: 'BBQ Pork Ribs',
    description: 'ซี่โครงหมูย่างซอส BBQ สูตรเด็ด เนื้อนุ่มหลุดกระดูก',
    price: 349,
    category: 'grill',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 16,
    name: 'ไก่ย่างจิ้มแจ่ว',
    nameEn: 'Grilled Chicken Jim Jaew',
    description: 'ไก่ย่างหอมถ่าน เสิร์ฟพร้อมน้ำจิ้มแจ่วรสเด็ด ข้าวเหนียว',
    price: 189,
    category: 'grill',
    image: '',
    popular: true,
    spicyLevel: 1,
  },

  // Seafood
  {
    id: 17,
    name: 'กุ้งเผาเกลือ',
    nameEn: 'Salt-Grilled Prawns',
    description: 'กุ้งแม่น้ำตัวใหญ่เผาเกลือ เสิร์ฟพร้อมซอสซีฟู้ด',
    price: 459,
    category: 'seafood',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 18,
    name: 'ปูนิ่มผัดผงกะหรี่',
    nameEn: 'Curry Soft Shell Crab',
    description: 'ปูนิ่มทอดกรอบผัดผงกะหรี่ หอมเครื่องเทศ',
    price: 379,
    category: 'seafood',
    image: '',
    popular: true,
    spicyLevel: 1,
  },
  {
    id: 19,
    name: 'ปลากะพงนึ่งมะนาว',
    nameEn: 'Steamed Sea Bass with Lime',
    description: 'ปลากะพงนึ่งมะนาวสด รสจัดจ้าน เนื้อปลาแน่นหวาน',
    price: 349,
    category: 'seafood',
    image: '',
    popular: false,
    spicyLevel: 3,
  },

  // Desserts
  {
    id: 20,
    name: 'ข้าวเหนียวมะม่วง',
    nameEn: 'Mango Sticky Rice',
    description: 'ข้าวเหนียวมูลนุ่มราดกะทิ พร้อมมะม่วงน้ำดอกไม้สุก',
    price: 139,
    category: 'dessert',
    image: '',
    popular: true,
    spicyLevel: 0,
  },
  {
    id: 21,
    name: 'ลาวาช็อกโกแลตเค้ก',
    nameEn: 'Chocolate Lava Cake',
    description: 'ช็อกโกแลตลาวาเค้กร้อนๆ ไหลทะลัก เสิร์ฟพร้อมไอศกรีมวานิลลา',
    price: 169,
    category: 'dessert',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 22,
    name: 'เครปเค้กชาเขียว',
    nameEn: 'Matcha Crepe Cake',
    description: 'เครปเค้กชาเขียวมัทฉะ ชั้นนุ่มละมุน หวานน้อย',
    price: 159,
    category: 'dessert',
    image: '',
    popular: false,
    spicyLevel: 0,
  },

  // Drinks
  {
    id: 23,
    name: 'ชาไทยเย็น',
    nameEn: 'Thai Iced Tea',
    description: 'ชาไทยเย็นหอมหวานมัน สูตรต้นตำรับ',
    price: 69,
    category: 'drink',
    image: '',
    popular: true,
    spicyLevel: 0,
  },
  {
    id: 24,
    name: 'น้ำมะพร้าวปั่น',
    nameEn: 'Coconut Smoothie',
    description: 'น้ำมะพร้าวปั่นเย็นๆ สดชื่น ใส่เนื้อมะพร้าวอ่อน',
    price: 89,
    category: 'drink',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 25,
    name: 'กาแฟลาเต้เย็น',
    nameEn: 'Iced Café Latte',
    description: 'กาแฟลาเต้เย็น ใช้เมล็ดอาราบิก้าคั่วกลาง',
    price: 99,
    category: 'drink',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
  {
    id: 26,
    name: 'สมูทตี้เบอร์รี่',
    nameEn: 'Mixed Berry Smoothie',
    description: 'สมูทตี้เบอร์รี่รวม สตรอว์เบอร์รี่ บลูเบอร์รี่ ราสเบอร์รี่',
    price: 119,
    category: 'drink',
    image: '',
    popular: false,
    spicyLevel: 0,
  },
];
